[package]
name = "everscale-types"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
base64 = "0.13"
thiserror = "1.0"
sha2 = "0.9"
smallvec = { version = "1.9", features = ["union"] }
hex = "0.4"

[profile.release]
debug = true
