[package]
name = "everscale-types"
description = "A set of primitive types and utilities for the Everscale blockchain."
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
repository = "https://github.com/broxus/everscale-types"
version = "0.1.0-pre.2"
edition = "2021"
rust-version = "1.65"
include = ["src/**/*.rs", "LICENSE-*", "README.md"]
license = "MIT OR Apache-2.0"

[dependencies]
base64 = { version = "0.13", optional = true }
hex = "0.4"
once_cell = "1.16"
rustc-hash = "1.1.0"
sha2 = "0.10"
smallvec = { version = "1.9", features = ["union"] }
thiserror = "1.0"

[dev-dependencies]
libc = "0.2"
base64 = "0.13"

[features]
default = ["base64"]

[profile.release]
debug = true
