[package]
name = "everscale-types"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
thiserror = "1.0"
rustc-hash = "1.1.0"
smallvec = { version = "1.9", features = ["union"] }
